name: greengreen
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^0.2.1

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  dotted_border: ^2.0.0+2
  google_maps_flutter: ^2.1.1
  geolocator: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo.png
    - assets/images/main_image.png
    - assets/images/my_location.png
    - assets/images/step_1.png
    - assets/images/step_2.png
    - assets/images/trash.png
    - assets/images/watch_1.png
    - assets/images/watch_2.png

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/AppleSDGothicNeoB.ttf
