name: greengreen
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.4
  geolocator: ^5.3.1
  flutter_polyline_points: ^0.2.1

  cupertino_icons: ^1.0.2
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true


  # To add asset to your application, add an asset section, like this:
  assets:
    - asset/images/Logo.png
    - asset/images/my_location.png
    - asset/images/step1.png
    - asset/images/step2.png
    - asset/images/trash.png
    - asset/images/watch1.png
    - asset/images/watch2.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
